name: Issue Report
description: If you have an issue you need help with
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: packname
    attributes:
      label: Pack name
      placeholder: "Create on a Potato PC: Sky Edition"
    validations:
      required: true 
