
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 725514
	#The name of the modpack
	modpackName = "Create on a Potato PC: Sky Edition"
	#The version of the modpack
	modpackVersion = "1.19.2-0.7.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

